#!/bin/bash

sr_cfg_file="/etc/schema-registry/schema-registry.properties"

: ${SCHEMA_REGISTRY_PORT:=8081}
: ${SCHEMA_REGISTRY_KAFKASTORE_TOPIC:=_schemas}
: ${SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL:=$ZOOKEEPER_PORT_2181_TCP_ADDR:$ZOOKEEPER_PORT_2181_TCP_PORT}
: ${SCHEMA_REGISTRY_DEBUG:=false}

export SCHEMA_REGISTRY_PORT
export SCHEMA_REGISTRY_KAFKASTORE_TOPIC
export SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
export SCHEMA_REGISTRY_DEBUG

echo '# Generated by schema_registry-docker.sh' > ${sr_cfg_file}
for var in $(env | grep '^SCHEMA_REGISTRY_' | sort); do
  key=$(echo $var | sed -r 's/SCHEMA_REGISTRY_(.*)=.*/\1/g' | tr A-Z a-z | tr _ .)
  value=$(echo $var | sed -r 's/.*=(.*)/\1/g')
  echo "${key}=${value}" >> ${sr_cfg_file}
done

for var in $(env | grep '^KAFKA[[:digit:]]*_PORT=' | sort); do
  broker=$(echo $var | cut -d'_' -f1)
  broker_ip=$(echo $var | cut -d':' -f2 | cut -c3-)
  broker_port=$(echo $var | cut -d':' -f3)
  while true; do
    printf 'Waiting for %s to come online\n' ${broker}
    echo "" >> /dev/tcp/${broker_ip}/${broker_port} && printf "${broker} is online\n" && break
    sleep 5
  done
done

exec /usr/bin/schema-registry-start ${sr_cfg_file}

